# Generated by Django 5.1.2 on 2026-01-16 09:23

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model('market', 'Category')

    category_map = {
        'Antiques / Art': [
            'Antique furniture',
            'Paintings',
            'Sculptures',
            'Collectibles',
            'Vintage decor',
            'Historical memorabilia',
        ],
        'Baby / Child': [
            'Strollers',
            'Car seats',
            'Clothing',
            'Toys',
            'Nursery furniture',
            'Maternity',
        ],
        'Beauty / Health / Wellness': [
            'Skincare',
            'Haircare',
            'Makeup',
            'Fragrances',
            'Supplements',
            'Massage & wellness',
        ],
        'Boats / Yachts / Jet skis': [
            'Boats',
            'Yachts',
            'Jet skis',
            'Boat accessories',
            'Trailers',
            'Navigation',
        ],
        'Books / Movies / Music': [
            'Books',
            'Movies',
            'Music',
            'Comics',
            'Vinyl',
            'CDs & DVDs',
        ],
        'Computer / Software': [
            'Adapter / Cables',
            'Computer / Tablets',
            'Laptops',
            'Desktops',
            'Printers / Monitors / Speakers',
            'Input / Readers',
            'Hard drives / Storage cards',
            'Networks',
            'PC Components',
            'Software',
            'USB Accessories',
        ],
        'Services': [
            'Repairs',
            'Cleaning',
            'Moving',
            'Tutoring',
            'Design',
            'IT services',
            'Event services',
        ],
        'Leisure / Instruments / Culinary': [
            'Musical instruments',
            'Camping & outdoor',
            'Crafts & DIY',
            'Kitchen appliances',
            'Cookware',
            'BBQ & grilling',
        ],
        'Games / Consoles': [
            'PlayStation',
            'Xbox',
            'Nintendo',
            'PC games',
            'Game accessories',
            'Retro games',
        ],
        'Home / Garden / Workshop': [
            'Furniture',
            'Tools',
            'Garden tools',
            'Plants',
            'DIY materials',
            'Lighting',
        ],
        'Cameras / TV / Multimedia': [
            'Cameras',
            'Lenses',
            'TVs',
            'Projectors',
            'Audio equipment',
            'Streaming devices',
        ],
        'Car accessories / Motorcycle parts': [
            'Car accessories',
            'Motorcycle parts',
            'Tires & wheels',
            'Car audio',
            'Helmets',
            'Maintenance',
        ],
        'Fashion / Accessories': [
            "Women's clothing",
            "Men's clothing",
            'Shoes',
            'Bags',
            'Accessories',
            'Jewelry',
        ],
        'Smartphones / Telephony': [
            'Smartphones',
            'Feature phones',
            'Phone accessories',
            'Wearables',
            'Smartwatches',
            'Repairs',
        ],
        'Games / Toys': [
            'Board games',
            'Building blocks',
            'Action figures',
            'Outdoor toys',
            'Educational toys',
            'Puzzles',
        ],
        'Sport / Sporting goods': [
            'Fitness',
            'Cycling',
            'Team sports',
            'Winter sports',
            'Water sports',
            'Outdoor gear',
        ],
        'Animals / Pet supplies': [
            'Dog supplies',
            'Cat supplies',
            'Fish & aquarium',
            'Bird supplies',
            'Small pets',
            'Pet food',
        ],
        'Watches / Jewelry': [
            'Watches',
            'Rings',
            'Necklaces',
            'Bracelets',
            'Earrings',
            'Luxury jewelry',
        ],
        'Home / Household / Hospitality': [
            'Kitchen',
            'Bathroom',
            'Cleaning',
            'Decor',
            'Bedding',
            'Restaurant equipment',
        ],
        'To give away': [
            'Furniture',
            'Electronics',
            'Clothing',
            'Baby items',
            'Books',
            'Miscellaneous',
        ],
    }

    created = {}
    for name in category_map.keys():
        category, _ = Category.objects.get_or_create(name=name, parent=None)
        created[name] = category

    for parent_name, subcategories in category_map.items():
        parent = created.get(parent_name)
        if not parent:
            continue
        for name in subcategories:
            Category.objects.get_or_create(name=name, parent=parent)


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_category_product_category'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_code=migrations.RunPython.noop),
    ]
