# Generated by Django 5.1.2 on 2026-01-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_seed_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rating',
        ),
    ]
