# Generated by Django 5.1.2 on 2026-01-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_order_payment_stripewebhookevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
