# Generated by Django 5.1.2 on 2026-01-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_conversation_product'),
        ('market', '0009_userprofile_birth_year_userprofile_gender_and_more'),
    ]

    operations = [
    ]
