# Generated by Django 5.1.2 on 2026-01-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_userprofile_phone_number_userprofile_zip_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
